export const minikitConfig = {
  accountAssociation: {
    header: "",
    payload: "",
    signature: "",
  },
  miniapp: {
    version: "1",
    name: "Base Chat",
    subtitle: "Private Messenger on Base",
    description: "Зашифрованный мессенджер на базе Base и FHE. Ваши сообщения видны только вам и получателю.",
    screenshotUrls: [`${process.env.ROOT_URL}/screenshot.png`],
    iconUrl: `${process.env.ROOT_URL}/icon.png`,
    splashImageUrl: `${process.env.ROOT_URL}/splash.png`,
    splashBackgroundColor: "#0052FF",
    homeUrl: process.env.ROOT_URL || "https://basechat-tau.vercel.app",
    webhookUrl: `${process.env.ROOT_URL}/api/webhook`,
    primaryCategory: "social",
    tags: ["messaging", "encryption", "fhenix", "privacy", "base"],
    heroImageUrl: `${process.env.ROOT_URL}/hero.png`,
    tagline: "Ваши сообщения только для вас",
    ogTitle: "Base Chat – приватный мессенджер",
    ogDescription: "Общайтесь с друзьями с полным шифрованием на базе Base",
    ogImageUrl: `${process.env.ROOT_URL}/og-image.png`,
  },
};